apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
