apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planmate-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - planmate
  selector:
    matchLabels:
      app: planmate
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
