apiVersion: v1
kind: Service
metadata:
  name: planmate-svc
  namespace: planmate
  labels:
    app: planmate
spec:
  selector:
    app: planmate
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
