# Default values - override these per environment
DOCKERHUB_USERNAME: viktorsirakov08
replicaCount: 2

image:
  repository: viktorsirakov08/planmate
  tag: v3
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  nodePort: 30081

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 90
  periodSeconds: 20

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SERVER_PORT: "8081"

postgres:
  image:
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  db: planmate
  storage: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

iam:
  replicaCount: 1
  image:
    repository: viktorsirakov08/iam-plannermate
    tag: v2
    pullPolicy: IfNotPresent
  service:
    port: 8085
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  readinessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 70
    periodSeconds: 10
    failureThreshold: 6
  livenessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 120
    periodSeconds: 20
    failureThreshold: 3

friend:
  replicaCount: 1
  image:
    repository: viktorsirakov08/friends-service
    tag: v1
    pullPolicy: IfNotPresent
  service:
    port: 8090
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  readinessProbe:
    tcpSocket:
      port: 8090
    initialDelaySeconds: 70
    periodSeconds: 10
    failureThreshold: 6
  livenessProbe:
    tcpSocket:
      port: 8090
    initialDelaySeconds: 120
    periodSeconds: 20
    failureThreshold: 3