# Default values - override these per environment
DOCKERHUB_USERNAME: viktorsirakov08
replicaCount: 2

image:
  repository: viktorsirakov08/planmate
  tag: v3
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  nodePort: 30081

database:
  url: "jdbc:postgresql://postgres-service:5432/planmate"
  username: "planmate"
  password: "planmate-password"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 90
  periodSeconds: 20

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_H2_CONSOLE_ENABLED: "false"
  SERVER_PORT: "8081"
  IAM_SERVICE_BASE_URL: "http://planner-iam:8085"
  AI_SERVICE_BASE_URL: "http://planmate-ai:8082"

iam:
  image:
    repository: viktorsirakov08/planner-iam
    tag: v1
    pullPolicy: IfNotPresent
  service:
    port: 8085
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  readinessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 70
    periodSeconds: 10
    failureThreshold: 6
  livenessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 120
    periodSeconds: 20
    failureThreshold: 3
