# Default values - override these per environment
replicaCount: 1

image:
  repository: viktorsirakov08/planmate
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  nodePort: 30081

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/planmate"
  SPRING_DATASOURCE_USERNAME: "planmate"
  SPRING_DATASOURCE_PASSWORD: "secret"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SERVER_PORT: "8081"