name: CI - Scheduler Service

on:
  push:
    branches: [main]
    paths:
<<<<<<< Updated upstream
      - 'main/**'
      - '.github/workflows/deploy-scheduler.yml'
=======
      - 'scheduler/**'
      - '.github/workflows/deploy-scheduler.yaml'
  pull_request:
    branches: [main]
>>>>>>> Stashed changes

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test --no-transfer-progress
        working-directory: scheduler